### ISSUE TITLE
Should it be the repositories job to save changes?

### ISSUE THREAD

**Issue by VictorioBerra** [CypressNorth/.NET-EFCore-GenericRepository#1]
Your services must be in control of the business transaction boundary.

http://mehdi.me/ambient-dbcontext-in-ef6/

**Comment by mombrea** [comment]
Hmm, this might depend on the bigger picture of your application.

I can see your concern, but this could be a naming issue depending on how you use this. The GenericRepository is really a Generic Base Service for accessing the DataContext. It could be argued that this setup helps enforce the business transaction boundary.

By having your service inherit from the GenericRepository, your service gets the basic methods which are saving changes at the time of the simple operation. When you need a more complicated, multi-step operation, you create that function in the implementing service or in a different class that uses the implementing service. In addition, you can override even the basic methods in the implementing service to do something different as needed. 

I'm not saying you're wrong, but it's largely up to how you're using this I think. We've debated this ourselves a few times.

**Comment by VictorioBerra** [comment]
This makes sense to me, I actually ported this over and ended up calling it GenericBaseService because that made way more sense based on its design.

Thanks.
